### ISSUE TITLE
juliandate  problems & EulerRotation function not included

### ISSUE THREAD

**Issue by jogehrig** [jeremyengels/interplanetary-porkchop#1]
Hi there and thanks for the nice tool!
I ran into a couple of issues:
first of all the juliandate function is handled stupidly by Matlab in that there are two functions with the same name.
To run your script one needs the **Aerospace toolbox** (which I happen to have access to but this could be worked around, I just wanted to document this here).
Using the aerospace toolboxes juliandate function, I needed to change the syntax from `juliandate(departure_1,'dd-mm-yyyy');` to `juliandate(departure_1,'dd-mmm-yyyy');`.

Another issue is that the function `EulerRotation` is referenced but not provided (I also can't find it anywhere on the internet) so I just hardcoded the Euler angles.

Expect a PR with a fix shortly (if it runs successfully) :D

**Comment by jogehrig** [comment]
Should be fixed by my changes made in my PR #2

**Comment by jeremyengels** [comment]
Hi Johannes, these functions can be found in my Utilities repo. Cheers

**Comment by jogehrig** [comment]
Ah, good to know! Then this all seems irrelevant :D
Happy holidays
